spring:
  rabbitmq: # @Bean으로 작성한 RabbitTemplate 쪽에서 ConnectionFactory 자동으로 생성
    host: localhost
    port: 5672
    username: admin
    password: admin123

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

token:
  secret:
    key: asdffsdsdsdfsadsdfsdsdfsdfdsfsfs # 32 character, minimum 256bit
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12